import fs from 'node:fs';
import path from 'node:path';

const defs = fs.readFileSync(new URL('./task-page-defs.tsv', import.meta.url), 'utf8').trim().split(/\r?\n/).map((line) => {
  const [routePath, folder, cls, menuSlug, taskSlug, columns, detailFields, model, detailMode, pageTitle, createTitle, detailTitle, labels] = line.split('|');
  return { routePath, folder, cls, menuSlug, taskSlug, columns, detailFields, model, detailMode, pageTitle, createTitle, detailTitle, labels: labels.split(',') };
});

const models = {
  custom: { listType: 'Record<string, unknown>', detailType: 'Record<string, unknown>', createType: 'Record<string, unknown>', imports: [], createFactory: '{} as New${CLS}Payload' },
  depolaraSevkIrsaliyeleri: { listType: 'DepolaraSevkIrsaliyeleriListeDto', detailType: 'DepolaraSevkIrsaliyeleriAyrintiDto', createType: 'DepolaraSevkIrsaliyeleriEkleDto', imports: [['liste-dtolari.model', 'DepolaraSevkIrsaliyeleriListeDto'], ['ayrinti-dtolari.model', 'DepolaraSevkIrsaliyeleriAyrintiDto'], ['ekle-dtolari.model', 'DepolaraSevkIrsaliyeleriEkleDto']], createFactory: "{ sevkedenAdSoyad: '', muhatapDepoNo: 0, iadedir: false, kalemler: [] }" },
  sevkIrsaliyeleri: { listType: 'SevkIrsaliyeleriListeDto', detailType: 'SevkIrsaliyeleriAyrintiDto', createType: 'SevkIrsaliyeleriEkleDto', imports: [['liste-dtolari.model', 'SevkIrsaliyeleriListeDto'], ['ayrinti-dtolari.model', 'SevkIrsaliyeleriAyrintiDto'], ['ekle-dtolari.model', 'SevkIrsaliyeleriEkleDto']], createFactory: "{ sevkedenAdSoyad: '', cariKod: '', iadedir: false, kalemler: [] }" },
  alisFaturalari: { listType: 'AlisFaturalariListeDto', detailType: 'AlisFaturalariAyrintiDto', createType: 'AlisFaturalariEkleDto', imports: [['liste-dtolari.model', 'AlisFaturalariListeDto'], ['ayrinti-dtolari.model', 'AlisFaturalariAyrintiDto'], ['ekle-dtolari.model', 'AlisFaturalariEkleDto']], createFactory: '{}' },
  depolardanMalKabulIrsaliyeleri: { listType: 'DepolardanMalKabulIrsaliyeleriListeDto', detailType: 'DepolardanMalKabulIrsaliyeleriAyrintiDto', createType: 'DepolardanMalKabulIrsaliyeleriEkleDto', imports: [['liste-dtolari.model', 'DepolardanMalKabulIrsaliyeleriListeDto'], ['ayrinti-dtolari.model', 'DepolardanMalKabulIrsaliyeleriAyrintiDto'], ['ekle-dtolari.model', 'DepolardanMalKabulIrsaliyeleriEkleDto']], createFactory: "{ seri: '', sira: 0, teslimAlanAdSoyad: '', kalemler: [] }" },
  girisFisleri: { listType: 'GirisFisleriListeDto', detailType: 'GirisFisleriAyrintiDto', createType: 'GirisFisleriEkleDto', imports: [['liste-dtolari.model', 'GirisFisleriListeDto'], ['ayrinti-dtolari.model', 'GirisFisleriAyrintiDto'], ['ekle-dtolari.model', 'GirisFisleriEkleDto']], createFactory: "{ olusturanAdSoyad: '', onaylayanAdSoyad: '', kalemler: [] }" },
  satisFaturalari: { listType: 'SatisFaturalariListeDto', detailType: 'SatisFaturalariAyrintiDto', createType: 'SatisFaturalariEkleDto', imports: [['liste-dtolari.model', 'SatisFaturalariListeDto'], ['ayrinti-dtolari.model', 'SatisFaturalariAyrintiDto'], ['ekle-dtolari.model', 'SatisFaturalariEkleDto']], createFactory: '{}' },
  alinanDepoSiparisleri: { listType: 'AlinanDepoSiparisleriListeDto', detailType: 'AlinanDepoSiparisleriAyrintiDto', createType: 'AlinanDepoSiparisleriEkleDto', imports: [['liste-dtolari.model', 'AlinanDepoSiparisleriListeDto'], ['ayrinti-dtolari.model', 'AlinanDepoSiparisleriAyrintiDto'], ['ekle-dtolari.model', 'AlinanDepoSiparisleriEkleDto']], createFactory: "{ muhatapDepoNo: 0, siparisVerenAdSoyad: '', kalemler: [] }" },
  alinanSiparisler: { listType: 'AlinanSiparislerListeDto', detailType: 'AlinanSiparislerAyrintiDto', createType: 'AlinanSiparislerEkleDto', imports: [['liste-dtolari.model', 'AlinanSiparislerListeDto'], ['ayrinti-dtolari.model', 'AlinanSiparislerAyrintiDto'], ['ekle-dtolari.model', 'AlinanSiparislerEkleDto']], createFactory: "{ cariKodu: '', siparisVerenAdSoyad: '', kalemler: [] }" },
  cikisFisleri: { listType: 'CikisFisleriListeDto', detailType: 'CikisFisleriAyrintiDto', createType: 'CikisFisleriEkleDto', imports: [['liste-dtolari.model', 'CikisFisleriListeDto'], ['ayrinti-dtolari.model', 'CikisFisleriAyrintiDto'], ['ekle-dtolari.model', 'CikisFisleriEkleDto']], createFactory: "{ olusturanAdSoyad: '', onaylayanAdSoyad: '', kalemler: [] }" },
  virman: { listType: 'VirmanListeDto', detailType: 'VirmanAyrintiDto', createType: 'VirmanEkleDto', imports: [['liste-dtolari.model', 'VirmanListeDto'], ['ayrinti-dtolari.model', 'VirmanAyrintiDto'], ['ekle-dtolari.model', 'VirmanEkleDto']], createFactory: "{ virmanYapanAdSoyad: '', kalemler: [] }" },
  sayimSonuclari: { listType: 'SayimSonuclariListeDto', detailType: 'SayimSonuclariAyrintiDto', createType: 'SayimSonuclariEkleDto', imports: [['liste-dtolari.model', 'SayimSonuclariListeDto'], ['ayrinti-dtolari.model', 'SayimSonuclariAyrintiDto'], ['ekle-dtolari.model', 'SayimSonuclariEkleDto']], createFactory: "{ sayanAdSoyad: '', kalemler: [] }" }
};

const root = path.resolve('src/app/features/dynamic-tasks/pages');
const presetImport = "COUNT_COLUMNS, COUNT_DETAIL_FIELDS, DEPOT_COLUMNS, DEPOT_DETAIL_FIELDS, DEPOT_WITH_BELGENO_COLUMNS, DOCUMENT_COLUMNS, DOCUMENT_DETAIL_FIELDS, DOCUMENT_WITH_BELGENO_COLUMNS, DOCUMENT_WITH_DURUM_DETAIL_FIELDS, EXIT_COLUMNS";
const listHtml = (f) => `<div class="card shadow">\n  <div class="card-body p-0">\n    @if (errorMessage) { <div class="alert alert-danger rounded-0 border-0 mb-0">{{ errorMessage }}</div> }\n    <div class="table-responsive">\n      <table class="table table-hover mb-0">\n        <thead class="thead-light"><tr>@for (column of columns; track column.key) { <th [class]="getColumnClass(column.align)">{{ column.label }}</th> }<th class="text-right">Islemler</th></tr></thead>\n        <tbody>@if (isLoading) { <tr><td [attr.colspan]="columns.length + 1" class="text-center py-4 text-muted">Yukleniyor...</td></tr> } @else if (!items.length) { <tr><td [attr.colspan]="columns.length + 1" class="text-center py-4 text-muted">Kayit bulunamadi.</td></tr> } @else { @for (item of items; track $index) { <tr>@for (column of columns; track column.key) { <td [class]="getColumnClass(column.align)">{{ formatValue(resolveValue(item, column.key, column.fallbackKey), column.format) }}</td> }<td class="text-right"><button class="btn btn-sm btn-primary" type="button" (click)="detailRequested.emit(item)"><i class="fa fa-search"></i></button></td></tr> } }</tbody>\n      </table>\n    </div>\n    <div class="d-flex flex-column flex-md-row align-items-md-center justify-content-between p-3 border-top"><div class="d-flex align-items-center mb-2 mb-md-0"><label class="mb-0 mr-2 small text-muted" for="${f}-page-size">Sayfa Boyutu</label><select id="${f}-page-size" class="form-control form-control-sm" style="width: 88px;" [value]="pageSize" (change)="pageSizeChanged.emit($any($event.target).value)">@for (option of pageSizeOptions; track option) { <option [value]="option">{{ option }}</option> }</select></div><div class="d-flex align-items-center"><span class="small text-muted mr-3">{{ rangeLabel }}</span><div class="btn-group btn-group-sm"><button class="btn btn-outline-secondary" type="button" [disabled]="currentPage === 1" (click)="previousPageRequested.emit()">Geri</button><button class="btn btn-outline-secondary" type="button" disabled>{{ currentPage }} / {{ totalPages }}</button><button class="btn btn-outline-secondary" type="button" [disabled]="currentPage === totalPages" (click)="nextPageRequested.emit()">Ileri</button></div></div></div>\n  </div>\n</div>\n`;
const createHtml = `@if (open) { <div class="modal fade show d-block" tabindex="-1" role="dialog" style="background: rgba(0, 0, 0, 0.35);"><div class="modal-dialog modal-lg modal-dialog-centered" role="document"><div class="modal-content border-0 shadow-lg"><div class="modal-header"><h5 class="modal-title text-primary font-weight-bold">{{ title }}</h5><button class="close" type="button" aria-label="Close" (click)="close.emit()"><span aria-hidden="true">&times;</span></button></div><div class="modal-body">@if (errorMessage) { <div class="alert alert-danger py-2">{{ errorMessage }}</div> }<div class="alert alert-info">Bu ekrana ozel form sonraki adimda kurulacak.</div><div class="border rounded p-3"><div class="small font-weight-bold text-primary mb-3">Bu ekrana ozel alanlar</div><div class="d-flex flex-wrap">@for (fieldLabel of fieldLabels; track fieldLabel) { <span class="badge badge-light border text-dark mr-2 mb-2 px-3 py-2">{{ fieldLabel }}</span> }</div></div></div><div class="modal-footer bg-white"><button class="btn btn-light" type="button" (click)="close.emit()">Kapat</button><button class="btn btn-success" type="button" [disabled]="isSubmitting" (click)="save.emit()">{{ isSubmitting ? 'Kaydediliyor...' : 'Kaydet' }}</button></div></div></div></div> }`;
const detailHtml = `@if (open) { <div class="modal fade show d-block" tabindex="-1" role="dialog" style="background: rgba(0, 0, 0, 0.35);"><div class="modal-dialog modal-xl modal-dialog-centered" role="document"><div class="modal-content border-0 shadow-lg"><div class="modal-body p-4 p-lg-5">@if (isLoading) { <p class="mb-0 text-muted">Detay yukleniyor...</p> } @else if (errorMessage) { <div class="alert alert-danger py-2 mb-0">{{ errorMessage }}</div> } @else if (detail) { <div class="d-flex justify-content-end mb-4"><button class="btn btn-primary mr-2" type="button"><i class="fa fa-print mr-1"></i>Yazdir</button><button class="btn btn-info text-white mr-2" type="button"><i class="fa fa-file-excel-o mr-1"></i>Excel'e Aktar</button><button class="btn btn-danger" type="button" (click)="close.emit()">Kapat</button></div><div class="row mb-4">@for (field of detailFields; track field.key) { <div class="col-md-3 mb-3"><div class="small text-muted mb-2">{{ field.label }}</div><div class="pb-1 border-bottom text-dark">{{ formatValue(resolveValue(detail, field.key), field.format) }}</div></div> }</div><div class="border rounded bg-white"><div class="table-responsive" style="max-height: 540px;"><table class="table table-borderless mb-0"><thead><tr class="border-bottom"><th class="small text-muted font-weight-normal"></th><th class="small text-muted font-weight-normal">Urun Kodu</th><th class="small text-muted font-weight-normal">Urun Adi</th><th class="small text-muted font-weight-normal text-center">Miktar</th><th class="small text-muted font-weight-normal text-center">Br.</th><th class="small text-muted font-weight-normal text-center">Sevk Edilen</th></tr></thead><tbody>@if (getDetailLines().length) { @for (line of getDetailLines(); track $index) { <tr style="background-color: #fde8e8;" class="border-bottom"><td class="font-weight-bold">{{ $index + 1 }}.</td><td>{{ line['stokKodu'] || '-' }}</td><td>{{ line['stokIsmi'] || '-' }}</td><td class="text-center">{{ getLineQuantity(line) }}</td><td class="text-center">{{ line['birim'] || '-' }}</td><td class="text-center">{{ line['sevkMiktari'] || 0 }}</td></tr> } } @else { <tr><td colspan="6" class="text-center text-muted py-4">Kalem bulunamadi.</td></tr> }</tbody></table></div></div>@if (getDetailStatus()) { <div class="mt-3 small text-muted">Durumu: {{ getDetailStatus() }}</div> } }</div></div></div></div> }`;

const ensure = (p) => fs.mkdirSync(p, { recursive: true });
const write = (p, c) => fs.writeFileSync(p, c);
const imp = (pairs, type) => pairs.filter(([, n]) => n.endsWith(type)).map(([f, n]) => `import { ${n} } from '../../../../core/models/${f}';`).join('\n');

for (const d of defs) {
  const m = models[d.model];
  const pageRoot = path.join(root, d.folder);
  ensure(path.join(pageRoot, 'components', `${d.folder}-list`));
  ensure(path.join(pageRoot, 'components', `${d.folder}-detail-dialog`));
  ensure(path.join(pageRoot, 'components', `new-${d.folder}-dialog`));
  ensure(path.join(pageRoot, 'data-access'));
  const createFactory = m.createFactory.replace('${CLS}', d.cls);
  const extra = d.columns === 'STOCK_TRANSFER_COLUMNS' ? "const STOCK_TRANSFER_COLUMNS = [...EXIT_COLUMNS, { key: 'durumu', label: 'Durumu' }];\n\n" : '';
  const detailSeg = d.detailMode === 'evrakNo' ? 'return [item.evrakNo];' : d.detailMode === 'record' ? "return [String((item as Record<string, unknown>)['seri'] ?? ''), Number((item as Record<string, unknown>)['sira'] ?? 0)];" : 'return [item.seri, item.sira];';
  write(path.join(pageRoot, `${d.folder}.models.ts`), `${imp(m.imports,'ListeDto')}\n${imp(m.imports,'AyrintiDto')}\n${imp(m.imports,'EkleDto')}\n\nexport type ${d.cls}ListItem = ${m.listType};\nexport type ${d.cls}Detail = ${m.detailType};\nexport type New${d.cls}Payload = ${m.createType};\n`);
  write(path.join(pageRoot, 'data-access', `${d.folder}.service.ts`), `import { Injectable } from '@angular/core';\n\nimport { TaskResourceService } from '../../../../../core/api/task-resource.service';\n\nexport const ${d.cls.toUpperCase()}_MENU_SLUG = '${d.menuSlug}';\nexport const ${d.cls.toUpperCase()}_TASK_SLUG = '${d.taskSlug}';\nexport type ${d.cls}TaskSlug = typeof ${d.cls.toUpperCase()}_TASK_SLUG;\n\n@Injectable({ providedIn: 'root' })\nexport class ${d.cls}Service extends TaskResourceService<${d.cls}TaskSlug> {\n  constructor() { super(${d.cls.toUpperCase()}_MENU_SLUG); }\n}\n`);
  write(path.join(pageRoot, `${d.folder}.ts`), `import { CommonModule } from '@angular/common';\nimport { Component, inject } from '@angular/core';\nimport { FormsModule } from '@angular/forms';\n\nimport { TaskPageBase } from '../../../../shared/task-pages/task-page.base';\nimport { ${presetImport} } from '../../../../shared/task-pages/task-page.presets';\nimport { ${d.cls}DetailDialogComponent } from './components/${d.folder}-detail-dialog/${d.folder}-detail-dialog';\nimport { ${d.cls}ListComponent } from './components/${d.folder}-list/${d.folder}-list';\nimport { New${d.cls}DialogComponent } from './components/new-${d.folder}-dialog/new-${d.folder}-dialog';\nimport { ${d.cls}Service, ${d.cls.toUpperCase()}_TASK_SLUG, ${d.cls}TaskSlug } from './data-access/${d.folder}.service';\nimport { ${d.cls}Detail, ${d.cls}ListItem, New${d.cls}Payload } from './${d.folder}.models';\n\n${extra}@Component({ selector: 'app-${d.folder}', imports: [CommonModule, FormsModule, ${d.cls}ListComponent, ${d.cls}DetailDialogComponent, New${d.cls}DialogComponent], templateUrl: './${d.folder}.html', styleUrl: './${d.folder}.scss' })\nexport class ${d.cls}PageComponent extends TaskPageBase<${d.cls}ListItem, ${d.cls}Detail, New${d.cls}Payload, ${d.cls}TaskSlug> {\n  protected readonly taskService = inject(${d.cls}Service);\n  protected readonly taskSlug = ${d.cls.toUpperCase()}_TASK_SLUG;\n  protected readonly pageTitle = '${d.pageTitle}';\n  protected readonly createTitle = '${d.createTitle}';\n  protected readonly detailTitle = '${d.detailTitle}';\n  protected readonly columns = ${d.columns};\n  protected readonly detailFields = ${d.detailFields};\n  protected readonly createFieldLabels = [${d.labels.map((x) => `'${x}'`).join(', ')}];\n  protected createEmptyCreateModel(): New${d.cls}Payload { return ${createFactory}; }\n  protected getDetailSegments(item: ${d.cls}ListItem): (string | number)[] { ${detailSeg} }\n}\n`);
  write(path.join(pageRoot, `${d.folder}.html`), `<div class="container-fluid"><div class="card shadow mb-4"><div class="card-body"><div class="d-flex flex-column flex-lg-row align-items-lg-center justify-content-between"><button class="btn btn-success mb-3 mb-lg-0" type="button" (click)="openCreateDialog()">Yeni</button><div class="d-flex flex-column flex-md-row align-items-md-center"><label class="mb-2 mb-md-0 mr-md-3 small font-weight-bold text-gray-700">Tarih Araligi</label><input type="date" class="form-control mb-2 mb-md-0 mr-md-2" [value]="startDate" [max]="maxDate" (change)="onStartDateChange($any($event.target).value)" /><span class="text-muted font-weight-bold mx-md-2 d-none d-md-inline">-</span><input type="date" class="form-control mt-2 mt-md-0 ml-md-2" [value]="endDate" [min]="startDate" [max]="maxDate" (change)="onEndDateChange($any($event.target).value)" /></div></div></div></div><app-${d.folder}-list [columns]="columns" [items]="pagedItems" [isLoading]="isLoading" [errorMessage]="errorMessage" [pageSize]="pageSize" [pageSizeOptions]="pageSizeOptions" [currentPage]="currentPage" [totalPages]="totalPages" [rangeLabel]="rangeLabel" (detailRequested)="openDetailDialog($event)" (pageSizeChanged)="onPageSizeChange($event)" (previousPageRequested)="goToPreviousPage()" (nextPageRequested)="goToNextPage()" /><app-new-${d.folder}-dialog [open]="isCreateDialogOpen" [form]="createForm" [title]="createTitle" [fieldLabels]="createFieldLabels" [errorMessage]="createErrorMessage" [isSubmitting]="isCreateSubmitting" (close)="closeCreateDialog()" (save)="submitCreate()" /><app-${d.folder}-detail-dialog [open]="isDetailDialogOpen" [detail]="selectedDetail" [title]="detailTitle" [detailFields]="detailFields" [isLoading]="isDetailLoading" [errorMessage]="detailErrorMessage" (close)="closeDetailDialog()" /></div>`);
  write(path.join(pageRoot, `${d.folder}.scss`), '');
  write(path.join(pageRoot, 'components', `${d.folder}-list`, `${d.folder}-list.ts`), `import { CommonModule } from '@angular/common';\nimport { Component, EventEmitter, Input, Output } from '@angular/core';\nimport { TaskPageColumn } from '../../../../../../shared/task-pages/task-page.types';\nimport { ${d.cls}ListItem } from '../../${d.folder}.models';\n@Component({ selector: 'app-${d.folder}-list', imports: [CommonModule], templateUrl: './${d.folder}-list.html' })\nexport class ${d.cls}ListComponent { @Input() columns: TaskPageColumn[] = []; @Input() items: ${d.cls}ListItem[] = []; @Input() isLoading = false; @Input() errorMessage = ''; @Input() pageSize = 10; @Input() pageSizeOptions: number[] = []; @Input() currentPage = 1; @Input() totalPages = 1; @Input() rangeLabel = ''; @Output() readonly detailRequested = new EventEmitter<${d.cls}ListItem>(); @Output() readonly pageSizeChanged = new EventEmitter<string>(); @Output() readonly previousPageRequested = new EventEmitter<void>(); @Output() readonly nextPageRequested = new EventEmitter<void>(); protected resolveValue(item: unknown | null, key: string, fallbackKey?: string): unknown { if (!item) return '-'; const d = item as Record<string, unknown>; const v = d[key]; if (v !== undefined && v !== null && v !== '') return v; return fallbackKey ? d[fallbackKey] ?? '-' : '-'; } protected formatValue(value: unknown, format: 'text' | 'date' | 'number' = 'text'): string { if (value === null || value === undefined || value === '') return '-'; if (format === 'date') { const p = new Date(String(value)); return Number.isNaN(p.getTime()) ? String(value) : p.toLocaleDateString('tr-TR'); } return String(value); } protected getColumnClass(align?: 'left' | 'center' | 'right'): string { return align === 'center' ? 'text-center' : align === 'right' ? 'text-right' : ''; } }\n`);
  write(path.join(pageRoot, 'components', `${d.folder}-list`, `${d.folder}-list.html`), listHtml(d.folder));
  write(path.join(pageRoot, 'components', `${d.folder}-detail-dialog`, `${d.folder}-detail-dialog.ts`), `import { CommonModule } from '@angular/common';\nimport { Component, EventEmitter, Input, Output } from '@angular/core';\nimport { TaskPageDetailField } from '../../../../../../shared/task-pages/task-page.types';\nimport { ${d.cls}Detail } from '../../${d.folder}.models';\n@Component({ selector: 'app-${d.folder}-detail-dialog', imports: [CommonModule], templateUrl: './${d.folder}-detail-dialog.html' })\nexport class ${d.cls}DetailDialogComponent { @Input() open = false; @Input() detail: ${d.cls}Detail | null = null; @Input() title = 'Detay'; @Input() isLoading = false; @Input() errorMessage = ''; @Input() detailFields: TaskPageDetailField[] = []; @Output() readonly close = new EventEmitter<void>(); protected resolveValue(item: unknown | null, key: string): unknown { return item ? (item as Record<string, unknown>)[key] ?? '-' : '-'; } protected formatValue(value: unknown, format: 'text' | 'date' | 'number' = 'text'): string { if (value === null || value === undefined || value === '') return '-'; if (format === 'date') { const p = new Date(String(value)); return Number.isNaN(p.getTime()) ? String(value) : p.toLocaleDateString('tr-TR'); } return String(value); } protected getDetailLines(): Record<string, unknown>[] { const lines = this.detail ? (this.detail as unknown as Record<string, unknown>)['kalemler'] : []; return Array.isArray(lines) ? lines as Record<string, unknown>[] : []; } protected getLineQuantity(line: Record<string, unknown>): number { return Number(line['siparisMiktari'] ?? line['onerilenSiparisMiktari'] ?? line['sevkMiktari'] ?? line['malKabulMiktari'] ?? line['sevkMalKabulFarkMiktari'] ?? line['virmanMiktari'] ?? 0); } protected getDetailStatus(): string { return this.detail ? String((this.detail as unknown as Record<string, unknown>)['durumu'] ?? '') : ''; } }\n`);
  write(path.join(pageRoot, 'components', `${d.folder}-detail-dialog`, `${d.folder}-detail-dialog.html`), detailHtml);
  write(path.join(pageRoot, 'components', `new-${d.folder}-dialog`, `new-${d.folder}-dialog.ts`), `import { CommonModule } from '@angular/common';\nimport { Component, EventEmitter, Input, Output } from '@angular/core';\nimport { New${d.cls}Payload } from '../../${d.folder}.models';\n@Component({ selector: 'app-new-${d.folder}-dialog', imports: [CommonModule], templateUrl: './new-${d.folder}-dialog.html' })\nexport class New${d.cls}DialogComponent { @Input() open = false; @Input() form!: New${d.cls}Payload; @Input() title = 'Yeni Kayit'; @Input() errorMessage = ''; @Input() isSubmitting = false; @Input() fieldLabels: string[] = []; @Output() readonly close = new EventEmitter<void>(); @Output() readonly save = new EventEmitter<void>(); }\n`);
  write(path.join(pageRoot, 'components', `new-${d.folder}-dialog`, `new-${d.folder}-dialog.html`), createHtml);
}

const barrel = defs.filter((d) => !['ArizaBildirim', 'DepolaraIadetenSevkler'].includes(d.routePath)).map((d) => `export { ${d.cls}PageComponent } from './${d.folder}/${d.folder}';`).join('\n');
write(path.join(root, 'explicit-dynamic-task-pages.ts'), `${barrel}\n`);
